name: Maven Package

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: WISE-Developers/versions
        path: versions
        token: ${{ secrets.WISE_PAT }}
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github

    - name: Load values from versions
      id: version-numbers
      shell: pwsh
      run: |
        $versions = ConvertFrom-StringData (Get-Content versions/versions.properties -raw)
        echo "::set-output name=prometheus_version::$($versions.prometheus)"
      
    - name: Update the version
      run: mvn versions:set -DnewVersion=${{ steps.version-numbers.outputs.prometheus_version }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Tag the repositories
      id: last-tags
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        API_TAG=$(git describe --tags --abbrev=0)
        echo "::set-output name=last_tag::$API_TAG"
        git tag -a ${{ steps.version-numbers.outputs.prometheus_version }} -m "Release on $(date +'%Y-%m-%d') for commit $(git rev-parse HEAD)"

    - name: Create Release Notes
      id: api-notes
      uses: mikepenz/release-changelog-builder-action@v3.5.0
      with:
        owner: WISE-Developers
        repo: WISE_Java_API
        toTag: ${{ steps.version-numbers.outputs.prometheus_version }}
#         fromTag: ${{ steps.last-tags.outputs.last_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.WISE_PAT }}
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.version-numbers.outputs.prometheus_version }}
        body: ${{ steps.api-notes.outputs.changelog }}
        files: target/*.jar
        tag_name: refs/tags/${{ steps.version-numbers.outputs.prometheus_version }}
